# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'samples/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      GOOGLE_MAPS_JS_SAMPLES_KEY: "${{ secrets.GOOGLE_MAPS_JS_SAMPLES_KEY }}"
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_MERGE_TOKEN }}
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.name 'googlemaps-bot'
          git config --global user.email 'googlemaps-bot@google.com'

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - run: npm i

      - name: Get Affected Workspaces
        id: get_workspaces
        run: bash samples/find-changes.sh ${{ github.event.before }}

      - name: Build Affected Projects
        if: steps.get_workspaces.outputs.changed_workspaces != ''
        run: |
          IFS=$'\n'
          AFFECTED_WORKSPACES_ARRAY=(${{ steps.get_workspaces.outputs.changed_workspaces }})
          
          echo "Building affected workspaces:"
          for workspace in "${AFFECTED_WORKSPACES_ARRAY[@]}"; do
            echo "  - samples/$workspace"
            rm -rf dist/samples/$workspace
            (cd samples/ && npm run build --workspace=$workspace)
          done

      - name: Generate Index
        run: bash samples/generate-index.sh

      - name: Get Deleted Workspaces
        id: get_deleted
        run: bash samples/find-deleted-subfolders.sh ${{ github.event.before }}

      - name: Remove Output for Deleted Folders
        if: steps.get_deleted.outputs.deleted_workspaces != ''
        run: |
          IFS=$'\n'
          DELETED_WORKSPACES_ARRAY=({{ steps.get_deleted.outputs.deleted_workspaces }})
          echo: "Removing deleted project output:"
          for workspace in "${DELETED_WORKSPACES_ARRAY[@]}"; do
            echo "  - samples/$workspace"
          done

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting

      - name: Create temporary branch
        run: git checkout -b temp-build-branch

      - name: Commit and Push Changes (to temp branch)
        run: |
          git add -A
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update dist folder [skip ci]"
          git push --force origin temp-build-branch

      - name: Trigger Create Release Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: dist-pr.yml
          ref: 'temp-build-branch'
          token: ${{ secrets.GH_APPROVER_TOKEN }} # Use the same token that pushed, it needs 'workflows: write' permissions
          inputs: '{ "source_run_id": "${{ github.run_id }}" }' # Optional: Pass the run ID for traceability
